name: kullanicilar_arama
description: Api de arama işlemi yapma

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  dio: ^4.0.6
  grock: ^0.1.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true